name: Citizens
main: net.citizensnpcs.Citizens
version: 1.1
authors: [fullwall, aPunch, NeonMaster]
softdepend: [Permissions]
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognized.
                    See /npc help for a list of commands.
    alchemist:
        description: Performs various Alchemist NPC-related commands.
        aliases: [alch]
        usage: |
                        The command was not recognized.
                        See /alchemist help for a list of commands.    
    blacksmith:
        description: Performs various Blacksmith NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /blacksmith help for a list of commands.           
    trader:
        description: Performs various Trader NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /trader help for a list of commands.
    guard:
        description: Performs various Guard NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /guard help for a list of commands.
    healer:
        description: Performs various Healer NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /healer help for a list of commands.
    wizard:
        description: Performs various Wizard NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /wizard help for a list of commands.
    quests:
        description: Performs player-quest related commands.
        usage: |
                        The command was not recognized.
                        See /citizens help for a list of commands.
    quester:
        description: Performs various Quester NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /quester help for a list of commands.
    toggle:
        description: Toggles between various NPC states.
        aliases: [t, tog]
        usage: |
                        The command was not recognized.
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                        The command was not recognized.
    waypoint:
        aliases: [wp, waypoints]
        description: Modifies waypoints.
        usage: |
                        The command was not recognized.
                    
permissions:
    citizens.*:
        default: false
        children:
            citizens.admin.*: true
            citizens.toggle.*: true
            citizens.trader.*: true
            citizens.basic.*: true
            citizens.guard.*: true
            citizens.blacksmith.*: true
            citizens.healer.*: true
            citizens.wizard.*: true
            citizens.quester.*: true
            citizens.waypoints.*: true
            citizens.npccount.unlimited: true
    citizens.admin.*:
        children:
            citizens.admin.info: true
            citizens.admin.reload: true
            citizens.admin.save: true
            citizens.admin.debug: true
            citizens.admin.removeall: true
            citizens.admin.toggleall: true
    citizens.toggle.*:
        children:
            citizens.toggle.help: true
            citizens.toggle.blacksmith: true
            citizens.toggle.guard: true
            citizens.toggle.healer: true
            citizens.toggle.trader: true
            citizens.toggle.quester: true
            citizens.toggle.wizard: true
    citizens.waypoints.*:
        children:
            citizens.waypoints.edit: true
            citizens.waypoints.modifier.*: true
    citizens.waypoints.modifier.*:
        children:
            citizens.waypoints.modifier.chat: true
            citizens.waypoints.modifier.effect: true
            citizens.waypoints.modifier.health: true
            citizens.waypoints.modifier.teleport: true
            citizens.waypoints.modifier.delay: true
    citizens.basic.*:
        children:
            citizens.basic.create: true
            citizens.basic.use.*: true
            citizens.basic.modify.*: true
    citizens.basic.use.*:
        children:
            citizens.basic.use.help: true
            citizens.basic.use.select: true
            citizens.basic.use.list: true
            citizens.basic.use.teleport: true
            citizens.basic.use.info: true
    citizens.basic.modify.*:
        children:
            citizens.basic.modify.move: true
            citizens.basic.modify.moveto: true
            citizens.basic.modify.copy: true
            citizens.basic.modify.remove: true
            citizens.basic.modify.rename: true
            citizens.basic.modify.color: true
            citizens.basic.modify.settext: true
            citizens.basic.modify.addtext: true
            citizens.basic.modify.resettext: true
            citizens.basic.modify.armor: true
            citizens.basic.modify.item: true
            citizens.basic.modify.lookat: true
            citizens.basic.modify.talkclose: true
            citizens.basic.modify.setowner: true
    citizens.alchemist.*:
        children:
            citizens.alchemist.use.*: true
            citizens.alchemist.modify.*: true
    citizens.alchemist.use.*:
        children:
            citizens.alchemist.use.interact: true
            citizens.alchemist.use.help: true
            citizens.alchemist.use.recipes.*: true
    citizens.alchemist.recipes.*:
        children:
            citizens.alchemist.use.recipes.select: true
            citizens.alchemist.use.recipes.view: true
    citizens.alchemist.modify.*:
        children:
            citizens.alchemist.modify.recipes: true
    citizens.blacksmith.*:
        children:
            citizens.blacksmith.use.*: true
    citizens.blacksmith.use.*:
        children:
            citizens.blacksmith.use.status: true
            citizens.blacksmith.use.help: true
            citizens.blacksmith.use.repair: true
    citizens.evils.*:
        children:
            citizens.evils.immune: true
    citizens.guard.*:
        children:
            citizens.guard.use.*: true
            citizens.guard.modify.*: true
    citizens.guard.use.*:
        children:
            citizens.guard.use.help: true
            citizens.guard.use.flags: true
    citizens.guard.modify.*:
        children:
            citizens.guard.modify.type: true
            citizens.guard.modify.flags: true
            citizens.guard.modify.radius: true
            citizens.guard.modify.aggro: true
    citizens.healer.*:
        children:
            citizens.healer.use.*: true
            citizens.healer.modify.*: true
    citizens.healer.use.*:
        children:
            citizens.healer.use.help: true
            citizens.healer.use.status: true
            citizens.healer.use.heal: true
    citizens.healer.modify.*:
        children:
            citizens.healer.modify.levelup: true  
    citizens.quester.*:
        children:
            citizens.quester.modify.*: true
            citizens.quester.use.*: true
    citizens.quester.use.*:
        children:
            citizens.quester.use.help: true
    citizens.quester.modify.*:
        children:
            citizens.quester.modify.questedit: true
            citizens.quester.modify.assignquest: true
            citizens.quester.modify.removequest: true
    citizens.trader.*:
        children:
            citizens.trader.use.*: true
            citizens.trader.modify.*: true
    citizens.trader.use.*:
        children:
            citizens.trader.use.help: true
            citizens.trader.use.showmoney: true
            citizens.trader.use.list: true
            citizens.trader.use.trade: true
    citizens.trader.modify.*:
        children:
            citizens.trader.modify.money: true
            citizens.trader.modify.unlimited: true
            citizens.trader.modify.stock: true
            citizens.trader.modify.clearstock: true 
    citizens.wizard.*:
        children:
            citizens.wizard.use.*: true
            citizens.wizard.modify.*: true
    citizens.wizard.use.*:
        children:
            citizens.wizard.use.help: true
            citizens.wizard.use.status: true
            citizens.wizard.use.locations: true
            citizens.wizard.use.interact: true
    citizens.wizard.modify.*:
        children:
            citizens.wizard.modify.mode: true
            citizens.wizard.modify.addloc: true
            citizens.wizard.modify.removeloc: true
            citizens.wizard.modify.unlimited: true
            citizens.wizard.modify.command: true