name: Citizens
main: net.citizensnpcs.Citizens
version: 1.2
authors: [fullwall, aPunch]
softdepend: [Vault]
commands:
    npc:
        description: Performs various NPC-related commands.
        usage: |
                    The command was not recognized.
                    See /npc help for a list of commands.  
    blacksmith:
        description: Performs various Blacksmith NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /blacksmith help for a list of commands.           
    trader:
        description: Performs various Trader NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /trader help for a list of commands.
    guard:
        description: Performs various Guard NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /guard help for a list of commands.
    healer:
        description: Performs various Healer NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /healer help for a list of commands.
    wizard:
        description: Performs various Wizard NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /wizard help for a list of commands.
    quest:
        description: Performs player-quest related commands.
        usage: |
                        The command was not recognized.
                        See /quest help for a list of commands.
    quester:
        description: Performs various Quester NPC-related commands.
        usage: |
                        The command was not recognized.
                        See /quester help for a list of commands.
    toggle:
        description: Toggles between various NPC states.
        aliases: [t, tog]
        usage: |
                        The command was not recognized.
    citizens:
        description: Performs Citizens-related commands.
        usage: |
                        The command was not recognized.
    waypoint:
        aliases: [wp, waypoints]
        description: Modifies waypoints.
        usage: |
                        The command was not recognized.
                    
permissions:
    citizens.*:
        default: op
        children:
            citizens.admin.override.*:
                 children:
                    citizens.admin.override.setowner: true
                    citizens.admin.override.remove: true
            citizens.admin.*:
                children:
                    citizens.admin.info: true
                    citizens.admin.reload: true
                    citizens.admin.save: true
                    citizens.admin.debug: true
                    citizens.admin.clean: true
                    citizens.admin.notifyupdates: true
            citizens.toggle.*:
                children:
                    citizens.toggle.help: true
                    citizens.toggle.all: true
                    citizens.toggle.blacksmith: true
                    citizens.toggle.guard: true
                    citizens.toggle.healer: true
                    citizens.toggle.trader: true
                    citizens.toggle.quester: true
                    citizens.toggle.wizard: true
            citizens.trader.*:
                children:
                    citizens.trader.use.*:
                        children:
                            citizens.trader.use.help: true
                            citizens.trader.use.list: true
                            citizens.trader.use.trade: true
                    citizens.trader.modify.*:
                        children:
                            citizens.trader.modify.unlimited: true
                            citizens.trader.modify.stock: true
                            citizens.trader.modify.clearstock: true
                            citizens.trader.modify.lock: true
                    citizens.trader.admin.*:
                        children:
                            citizens.trader.admin.useglobal: true
            citizens.basic.*:
                children:
                        citizens.basic.create: true
                        citizens.basic.use.*:
                            children:
                                citizens.basic.use.help: true
                                citizens.basic.use.select: true
                                citizens.basic.use.list: true
                                citizens.basic.use.teleport: true
                                citizens.basic.use.info: true
                                citizens.basic.use.showmoney: true
                        citizens.basic.modify.*:
                            children:
                                citizens.basic.modify.select: true
                                citizens.basic.modify.move: true
                                citizens.basic.modify.moveto: true
                                citizens.basic.modify.copy: true
                                citizens.basic.modify.remove: true
                                citizens.basic.modify.rename: true
                                citizens.basic.modify.color: true
                                citizens.basic.modify.settext: true
                                citizens.basic.modify.addtext: true
                                citizens.basic.modify.resettext: true
                                citizens.basic.modify.equip: true
                                citizens.basic.modify.lookat: true
                                citizens.basic.modify.talkclose: true
                                citizens.basic.modify.setowner: true
                                citizens.basic.modify.money: true
                                citizens.basic.modify.remove.*:
                                    children:
                                        citizens.basic.modify.remove: true
                                        citizens.basic.modify.remove.all: true
            citizens.guard.*:
                children:
                    citizens.guard.use.*:
                        children:
                            citizens.guard.use.help: true
                            citizens.guard.use.flags: true
                    citizens.guard.modify.*:
                        children:
                            citizens.guard.modify.type: true
                            citizens.guard.modify.flags: true
                            citizens.guard.modify.radius: true
                            citizens.guard.modify.aggro: true
            citizens.blacksmith.*:
                children:
                    citizens.blacksmith.use.*:
                        children:
                            citizens.blacksmith.use.status: true
                            citizens.blacksmith.use.help: true
                            citizens.blacksmith.use.repair: true
            citizens.evils.*:
                children:
                    citizens.evils.immune: true
            citizens.healer.*:
                children:
                    citizens.healer.use.*:
                        children:
                            citizens.healer.use.help: true
                            citizens.healer.use.status: true
                            citizens.healer.use.heal: true
                    citizens.healer.modify.*:
                        children:
                            citizens.healer.modify.levelup: true  
            citizens.wizard.*:
                children:
                    citizens.wizard.use.*:
                        children:
                            citizens.wizard.use.help: true
                            citizens.wizard.use.status: true
                            citizens.wizard.use.locations: true
                            citizens.wizard.use.interact: true
                    citizens.wizard.modify.*:
                        children:
                            citizens.wizard.modify.mode: true
                            citizens.wizard.modify.addloc: true
                            citizens.wizard.modify.removeloc: true
                            citizens.wizard.modify.unlimited: true
            citizens.quester.*:
                children:
                    citizens.quester.admin.*:
                        children:
                            citizens.quester.admin.quests.save: true
                            citizens.quester.admin.quests.giveplayer: true
                            citizens.quester.admin.quests.clear: true
                    citizens.quester.use.*:
                        children:
                            citizens.quester.use.help: true
                            citizens.quester.use.quests.*:
                                children:
                                    citizens.quester.use.quests.help: true
                                    citizens.quester.use.quests.view: true
                                    citizens.quester.use.quests.abort: true
                                    citizens.quester.use.quests.status: true
                    citizens.quester.modify.*:
                        children:
                            citizens.quester.modify.quests.*:
                                children:
                                    citizens.quester.modify.quests.assign: true
                                    citizens.quester.modify.quests.remove: true
            citizens.waypoints.*:
                children:
                    citizens.waypoints.edit: true
                    citizens.waypoints.modifier.*:
                        children:
                            citizens.waypoints.modifier.chat: true
                            citizens.waypoints.modifier.effect: true
                            citizens.waypoints.modifier.health: true
                            citizens.waypoints.modifier.teleport: true
                            citizens.waypoints.modifier.delay: true
            citizens.npccount.unlimited: true